version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: concert_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concertdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: concert_redis
    restart: always
    ports:
      - "6379:6379"

  springboot-backend:
    build: ./backend  # Spring Boot Dockerfile olmalı
    container_name: concert_backend
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/concertdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  scraper:
    build: ./scraper  # Python veya Node.js scraper servisin Dockerfile'ı
    container_name: concert_scraper
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: concertdb

volumes:
  pgdata:
